name: Deploy to Dokku Dev

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - 'master'
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
      - '.gitignore'

jobs:
  deploy:
    runs-on: ubuntu-20.04-self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
            fetch-depth: 0
      - id: deploy
        name: Deploy to dokku
        uses: NickVolynkin/dokku-deploy-github-action@allow-multiple-deployments
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
            dokku-host: job-re-runner-dev.tarantool.io
            app-name: job-re-runner-dev
            git-push-flags: '--force'
